# Generated by Django 3.1.1 on 2020-09-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NoName', max_length=50, verbose_name='Name')),
                ('money', models.IntegerField(max_length=7, verbose_name='money')),
                ('date', models.DateTimeField(verbose_name='Дата доната')),
            ],
        ),
    ]