# Generated by Django 3.1.1 on 2020-09-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tops',
            name='money',
            field=models.IntegerField(verbose_name='money'),
        ),
    ]
